config/routes.rb
Rails.application.routes.draw do
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  devise_for :doctors
  root 'home#index'
  resources :doctors, only: [:show, :edit, :update] do
    get 'create_patient', on: :member
    post 'create_patient', on: :member
    get 'patient_info', on: :member
    get 'book_appintment', on: :member
    post 'create_appointment', on: :member
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/admin_user.rb
class AdminUser < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/appointment.rb
class Appointment < ApplicationRecord
  belongs_to :doctor
  belongs_to :patient
end

app/models/doctor.rb
class Doctor < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_attached_file :avatar, styles: { medium: "300x300>", thumb: "100x100>" }, default_url: "/images/:style/missing.png"
  validates_attachment_content_type :avatar, content_type: /\Aimage\/.*\z/
  has_many :doctor_patients
  has_many :patients, through: :doctor_patients
  has_many :appointments, dependent: :destroy
  accepts_nested_attributes_for :patients

end

app/models/doctor_patient.rb
class DoctorPatient < ApplicationRecord
  belongs_to :doctor
  belongs_to :patient
  after_create :doctor_added

  def doctor_added
    DoctorActivityMailer.with(patient: self.patient_id).patient_added_activity_email.deliver_now
  end
end

app/models/patient.rb
class Patient < ApplicationRecord
  has_many :doctor_patients
  has_many :doctors, through: :doctor_patients
  has_many :appointments, dependent: :destroy
  accepts_nested_attributes_for :doctors
  validates :email, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  protected
    def after_sign_in_path_for(resource)
      request.env['omniauth.origin'] || stored_location_for(resource) || doctor_path(resource)
    end
end

app/controllers/doctors_controller.rb
class DoctorsController < ApplicationController
  before_action :authenticate_doctor!
  before_action :set_doctor, only: [:show, :edit, :update, :create_patient, :patient_info, :create_appointment, :book_appintment]

  # GET /doctors/1
  # GET /doctors/1.json
  def show
    @patients = @doctor.patients
  end

  # GET /doctors/1/edit
  def edit
  end

  # PATCH/PUT /doctors/1
  # PATCH/PUT /doctors/1.json
  def update
    respond_to do |format|
      if @doctor.update(doctor_params)
        format.html { redirect_to @doctor, notice: 'Doctor was successfully updated.' }
        format.json { render :show, status: :ok, location: @doctor }
      else
        format.html { render :edit }
        format.json { render json: @doctor.errors, status: :unprocessable_entity }
      end
    end
  end

  def create_patient
    if request.get?
    else
      respond_to do |format|
        if @doctor.update(doctor_params)
          format.html { redirect_to create_patient_doctor_path(@doctor), notice: 'patient is successfully created.' }
          format.json { render :create_patient, status: :ok, location: @doctor }
        else
          format.html { render :create_patient }
          format.json { render json: @doctor.errors, status: :unprocessable_entity }
        end
      end
    end
  end

  def patient_info
    @patient = Patient.find(params[:patient_id])
    @appointments =  @patient.appointments
  end

  def book_appintment
    @patient = Patient.find(params[:patient_id])
    @appointment = Appointment.new
  end

  def create_appointment
    @patient = Patient.find(params[:patient_id])
    # @appointment = @doctor.appointments.new
    @appointment = @patient.appointments.new
    @appointment.doctor_id = @doctor.id
    @appointment.start_date = params[:appointment][:start_date].to_date
    @appointment.start_date = params[:appointment][:start_time].to_time
    @appointment.start_date = params[:appointment][:end_time].to_time
    respond_to do |format|
      if @appointment.save(appointment_params)
        format.html { redirect_to patient_info_doctor_path(id: @doctor.id, patient_id: @appointment.patient.id ), notice: 'appointment is successfully created.' }
        format.json { render :book_appintment, status: :ok, location: @appointment }
      else
        format.html { render :book_appintment }
        format.json { render json: @appointment.errors, status: :unprocessable_entity }
      end
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_doctor
      @doctor = Doctor.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def doctor_params
      params.require(:doctor).permit(:email, :f_name, :l_name, :avatar, :patients_attributes => [:id, :email, :f_name, :l_name, :disease])
    end

    def appointment_params
      params.require(:appointment).permit(:start_date, :start_time, :end_time, :doctor_id,:patient_id)
    end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/doctors_helper.rb
module DoctorsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/doctors/_form.html.erb
<%= form_with(model: doctor, local: true) do |form| %>
  <% if doctor.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(doctor.errors.count, "error") %> prohibited this doctor from being saved:</h2>

      <ul>
      <% doctor.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :email %>
    <%= form.text_field :email, id: :doctor_email %>
  </div>

  <div class="field">
    <%= form.label :f_name %>
    <%= form.text_field :f_name, id: :doctor_f_name %>
  </div>

  <div class="field">
    <%= form.label :l_name %>
    <%= form.text_field :l_name, id: :doctor_l_name %>
  </div>

  <div class="field">
    <%= form.label :avatar, "Select Profile Image" %>
    <%= form.file_field :avatar %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/doctors/book_appintment.html.erb
<%= form_for(@appointment, method: :post, url: create_appointment_doctor_path(@doctor)) do |form| %>
  <% if @appointment.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@appointment.errors.count, "error") %> prohibited this @appointment from being saved:</h2>

      <ul>
      <% @appointment.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :start_date %>
    <%= form.date_field :start_date %>
  </div>

  <div class="field">
    <%= form.label :start_time %>
    <%= form.time_field :start_time %>
  </div>

  <div class="field">
    <%= form.label :end_time %>
    <%= form.time_field :end_time %>
  </div>

  <%= hidden_field_tag :patient_id, @patient.id %>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/doctors/create_patient.html.erb
<%= form_for @doctor, method: :post, url: create_patient_doctor_path do |form| %>

  <% if @doctor.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@doctor.errors.count, "error") %> prohibited this doctor from being saved:</h2>

      <ul>
      <% @doctor.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <%= form.fields_for :patients, @doctor.patients.new do |pat| %>
    <div class="field">
      <%= pat.label :email, "Email" %>
      <%= pat.text_field :email %>
    </div>
    <div class="field">
      <%= pat.label :f_name, "First Name" %>
      <%= pat.text_field :f_name %>
    </div>
    <div class="field">
      <%= pat.label :l_name, "Last Name" %>
      <%= pat.text_field :l_name %>
    </div>
    <div class="field">
      <%= pat.label :disease %>
      <%= pat.text_field :disease %>
    </div>
  <% end %>

  <div class="actions">
    <%= form.submit "Create Patient" %>
  </div>
<% end %>


<%= link_to "Back", doctor_path(@doctor) %>

app/views/doctors/edit.html.erb
<h1>Editing Doctor</h1>

<%= render 'form', doctor: @doctor %>

<%= link_to 'Show', @doctor %> 

app/views/doctors/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Doctors</h1>

<table>
  <thead>
    <tr>
      <th>Email</th>
      <th>F name</th>
      <th>L name</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @doctors.each do |doctor| %>
      <tr>
        <td><%= doctor.email %></td>
        <td><%= doctor.f_name %></td>
        <td><%= doctor.l_name %></td>
        <td><%= link_to 'Show', doctor %></td>
        <td><%= link_to 'Edit', edit_doctor_path(doctor) %></td>
        <td><%= link_to 'Destroy', doctor, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Doctor', new_doctor_path %>

app/views/doctors/new.html.erb
<h1>New Doctor</h1>

<%= render 'form', doctor: @doctor %>

<%= link_to 'Back', doctors_path %>

app/views/doctors/patient_info.html.erb
<p id="notice"><%= notice %></p>
<h1>Patient Info</h1>
<table class="table table-striped">
  <tbody>
    <tr>
      <th scope="col">Email</th>
      <td><%= @patient.email %></td>
    </tr>
    <tr>
      <th scope="col">First Name</th>
      <td><%= @patient.f_name %></td>
    </tr>
    <tr>
      <th scope="col">Last Name</th>
      <td><%= @patient.l_name %></td>
    </tr>
    <tr>
      <th scope="col">Disease</th>
      <td>
        <%= @patient.disease %>
      </td>
    </tr>
  <tbody>
</table>
<%= link_to "Book Appointment", book_appintment_doctor_path(id: @doctor, patient_id: @patient.id) %>

<h1>Appointments</h1>

<table class="table">
  <thead>
    <tr>
      <th scope="col">Start date</th>
      <th scope="col"> start time</th>
      <th scope="col">end time</th>
      <th scope="col">doctor</th>
    </tr>
  </thead>
  <tbody>
    <% @appointments.each do |appointment| %>
      <tr>
        <th><%= appointment.start_date %> </th>
        <td><%= appointment.start_time %></td>
        <td><%= appointment.end_time %></td>
        <td><%= appointment.doctor.f_name %></td>        
      </tr>
    <% end %>
  </tbody>
</table>

app/views/doctors/show.html.erb
<p id="notice"><%= notice %></p>
<h1>Doctor Info</h1>
<table class="table table-striped">
  <tbody>
    <tr>
      <th scope="col">Email</th>
      <td><%= @doctor.email %></td>
    </tr>
    <tr>
      <th scope="col">First Name</th>
      <td><%= @doctor.f_name %></td>
    </tr>
    <tr>
      <th scope="col">Last Name</th>
      <td><%= @doctor.l_name %></td>
    </tr>
    <tr>
      <th scope="col">Image</th>
      <td>
        <% if @doctor.avatar.exists? %>
          <%= image_tag @doctor.avatar.url(:thumb) %>
        <% end %>
      </td>
    </tr>
  <tbody>
</table>

<%= link_to 'Edit', edit_doctor_path(@doctor), class: "btn btn-primary" %>



<%= link_to "Create Patient", create_patient_doctor_path(@doctor), class: "btn btn-primary" %>
<div class="row">
  <div class="col-md-6">
    <h2>Patient Info</h2>
  </div>
</div>

<table class="table">
  <thead>
    <tr>
      <th scope="col">First Name</th>
      <th scope="col">Last Name</th>
      <th scope="col">Email</th>
      <th scope="col">Disease</th>
      <th scope="col">Show</th>
    </tr>
  </thead>
  <tbody>
    <% @patients.each do |patient| %>
      <tr>
        <th><%= patient.f_name %> </th>
        <td><%= patient.l_name %></td>
        <td><%= patient.email %></td>
        <td><%= patient.disease %></td>
        <td><%= link_to 'show', patient_info_doctor_path(id: @doctor, patient_id: patient.id) %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/home/index.html.erb
<h1>Welcome to the hospital management</h1>
<% if doctor_signed_in? %>
  <%= link_to "Logout", destroy_doctor_session_path, method: :delete %>
<% else %>
  <%= link_to "Login", new_doctor_session_path %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Hospital</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>
  <p class="notice"><%= notice %></p>
  <p class="alert"><%= alert %></p>
  <body>
    <%= yield %>
  </body>
</html>